apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprormq01
  labels:
    app: vprormq01
spec: 
  selector:
    matchLabels:
      app: vprormq01
  replicas: 1
  template:
    metadata:
      labels:
        app: vprormq01
    spec:
      containers:
        - name: vprormq01
          image: rabbitmq
          ports: 
            - name: vprormq01-port
              containerPort: 5672
          env:
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: rmq-pass
            - name : RABBITMQ_DEFAULT_USER
              value: "guest"