apiVersion: apps/v1
kind: Service
metadata:
  name: vproapp-service
spec:
  selector:
    app: vproapp-service
  ports:
    - port: 80
      targetPort: vproapp-port
      protocol: TCP
  type: LoadBalancer
